<a href="https://colab.research.google.com/github/shyamsudhir05/DAV_Project/blob/main/Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DATA COMBINATION FOR BUSINESS UNDERSTANDING (This concept is not
# actual lab program but you have to understand the concept that’s it)
# Now that we have understood and explored the dataset, suppose the business gives us
# additional information stored in different tables. We need to combine that information to
# perform better analysis. This is called Data Combination.
# It covers:
# 1. Concatenation
# 2. Merging
# 3. Joining
# 4. GroupBy
# 5. Pivot Table

In [1]:
import pandas as pd

In [2]:
# 1. CREATE SALES DATA
df = pd.DataFrame({
    "Order Date": [
        "2024-01-10",
        "2024-01-15",
        "2024-02-05",
        "2024-02-12",
        "2024-03-01",
        "2024-03-15",
        "2024-04-10",
        "2024-04-20",
        "2024-05-05",
        "2024-01-15"
    ],
    "Product Name": [
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Laptop",
        "Monitor",
        "Mouse",
        "Printer",
        "Smartwatch",
        "Mouse"
    ],
    "Category": [
        "Electronics",
        "Accessories",
        "Office",
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Office",
        "Electronics",
        "Accessories"
    ],
    "Region": [
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South"
    ],
    "Quantity": [
        2,
        5,
        3,
        4,
        1,
        2,
        6,
        2,
        3,
        5
    ],
    "Sales": [
        50000,
        2500,
        9000,
        30000,
        55000,
        16000,
        3000,
        6000,
        45000,
        2500
    ],
    "Profit": [
        10000,
        500,
        1500,
        6000,
        11000,
        3000,
        None,
        1000,
        9000,
        500
    ]
})

In [3]:
# 2. CONCATENATION

new_sales = pd.DataFrame({
    "Order Date": [
        "2024-06-01",
        "2024-06-05",
        "2024-06-10"
    ],
    "Product Name": [
        "Laptop",
        "Mouse",
        "Printer"
    ],
    "Category": [
        "Electronics",
        "Accessories",
        "Office"
    ],
    "Region": [
        "North",
        "South",
        "East"
    ],
    "Quantity": [
        2,
        4,
        3
    ],
    "Sales": [
        60000,
        2000,
        9000
    ],
    "Profit": [
        12000,
        400,
        1800
    ]
})

print("NEW SALES DATA")

display(new_sales)
combined_df = pd.concat(
    [df, new_sales],
    ignore_index=True
)
print("-"*69)
print("CONCATENATED DATA")
display(combined_df)

NEW SALES DATA

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-06-01       Laptop  Electronics  North         2  60000   12000
1  2024-06-05        Mouse  Accessories  South         4   2000     400
2  2024-06-10      Printer       Office   East         3   9000    1800

---------------------------------------------------------------------
CONCATENATED DATA

    Order Date Product Name     Category Region  Quantity  Sales   Profit
0   2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1   2024-01-15        Mouse  Accessories  South         5   2500    500.0
2   2024-02-05      Printer       Office   East         3   9000   1500.0
3   2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4   2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5   2024-03-15      Monitor  Accessories  South         2  16000   3000.0
6   2024-04-10        Mouse  Accessories   East         6   3000      NaN
7   2024-04-20      Printer       Office   West         2   6000   1000.0
8   2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9   2024-01-15        Mouse  Accessories  South         5   2500    500.0
10  2024-06-01       Laptop  Electronics  North         2  60000  12000.0
11  2024-06-05        Mouse  Accessories  South         4   2000    400.0
12  2024-06-10      Printer       Office   East         3   9000   1800.0

In [4]:
# 3. MERGING

product_info = pd.DataFrame({
    "Product Name": [
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Monitor"
    ],
    "Supplier": [
        "Dell",
        "Logitech",
        "HP",
        "Samsung",
        "LG"
    ],
    "Discount": [
        10,
        5,
        15,
        8,
        12
    ]
})

print("PRODUCT INFORMATION")
display(product_info)
merged_df = pd.merge(
    df,
    product_info,
    on="Product Name",
    how="left"
)
print("-"*88)
print("MERGED DATA")
display(merged_df)

PRODUCT INFORMATION

  Product Name  Supplier  Discount
0       Laptop      Dell        10
1        Mouse  Logitech         5
2      Printer        HP        15
3       Tablet   Samsung         8
4      Monitor        LG        12

----------------------------------------------------------------------------------------
MERGED DATA

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Supplier,Discount
0,2024-01-10,Laptop,Electronics,North,2,50000,10000.0,Dell,10.0
1,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0
2,2024-02-05,Printer,Office,East,3,9000,1500.0,HP,15.0
3,2024-02-12,Tablet,Electronics,West,4,30000,6000.0,Samsung,8.0
4,2024-03-01,Laptop,Electronics,North,1,55000,11000.0,Dell,10.0
5,2024-03-15,Monitor,Accessories,South,2,16000,3000.0,LG,12.0
6,2024-04-10,Mouse,Accessories,East,6,3000,NaN,Logitech,5.0
7,2024-04-20,Printer,Office,West,2,6000,1000.0,HP,15.0
8,2024-05-05,Smartwatch,Electronics,North,3,45000,9000.0,NaN,NaN
9,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0

In [5]:
# 4. JOINING

region_info = pd.DataFrame(
{
"Region_Manager": [
"Manager A",
"Manager B",
"Manager C",
"Manager D"
]
},

index=[
"North",
"South",
"East",
"West"
]
)

print("REGION INFORMATION")
display(region_info)
df_region = df.set_index("Region")
joined_df = df_region.join(region_info)
print("-"*80)
print("JOINED DATA")
display(joined_df)

REGION INFORMATION

      Region_Manager
North      Manager A
South      Manager B
East       Manager C
West       Manager D

--------------------------------------------------------------------------------
JOINED DATA

,Order Date,Product Name,Category,Quantity,Sales,Profit,Region_Manager
Region,,,,,,,
North,2024-01-10,Laptop,Electronics,2,50000,10000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B
East,2024-02-05,Printer,Office,3,9000,1500.0,Manager C
West,2024-02-12,Tablet,Electronics,4,30000,6000.0,Manager D
North,2024-03-01,Laptop,Electronics,1,55000,11000.0,Manager A
South,2024-03-15,Monitor,Accessories,2,16000,3000.0,Manager B
East,2024-04-10,Mouse,Accessories,6,3000,NaN,Manager C
West,2024-04-20,Printer,Office,2,6000,1000.0,Manager D
North,2024-05-05,Smartwatch,Electronics,3,45000,9000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B

In [6]:
# 5. GROUPBY

region_sales = df.groupby(
"Region"
)["Sales"].sum()

print("TOTAL SALES BY REGION")
display(region_sales)

TOTAL SALES BY REGION

Region
East      12000
North    150000
South     21000
West      36000
Name: Sales, dtype: int64

In [7]:
# 6. PIVOT TABLE

pivot_table = pd.pivot_table(
df,
values="Sales",
index="Category",
columns="Region",
aggfunc="sum",
fill_value=0
)
print("PIVOT TABLE")
display(pivot_table)

PIVOT TABLE

Region       East   North  South   West
Category
Accessories  3000       0  21000      0
Electronics     0  150000      0  30000
Office       9000       0      0   6000